Repository iotaledger/explorer, pull requests merged in 2022-11, with the labels that each got.

#568 Fix: Add color to association label for dark mode
  client/src/app/components/stardust/AssociatedOutputs.scss
  client/src/app/components/stardust/AssociatedOutputs.tsx
  client/src/app/components/stardust/AssociationSection.scss
  client/src/app/components/stardust/AssociationSection.tsx
Labels: type:fix, type:ui, network:testnet, network:shimmer

#569 Fix(css): Fix Analytic stats info boxes css
  client/src/app/routes/stardust/landing/AnalyticStats.scss
  client/src/app/routes/stardust/landing/AnalyticStats.tsx
Labels: type:ui, network:testnet, network:shimmer

#567 Feat: Implement basic TX history download based on period-to-date
  api/package-lock.json
  api/package.json
  api/src/models/api/stardust/ITransactionHistoryDownloadBody.ts
  api/src/models/api/stardust/ITransactionHistoryDownloadResponse.ts
  api/src/models/api/stardust/ITransactionHistoryRequest.ts
  api/src/models/api/stardust/ITransactionHistoryResponse.ts
  api/src/routes.ts
  api/src/routes/stardust/transactionhistory/download/post.ts
  api/src/services/stardust/chronicleService.ts
  api/src/utils/apiHelper.ts
  client/src/app/components/Modal.tsx
  client/src/app/components/stardust/DownloadModal.scss
  client/src/app/components/stardust/DownloadModal.tsx
  client/src/app/components/stardust/history/TransactionHistory.scss
  client/src/app/components/stardust/history/TransactionHistory.tsx
  client/src/helpers/fetchHelper.ts
  client/src/models/api/IRawResponse.ts
  client/src/services/apiClient.ts
  client/src/services/stardust/stardustApiClient.ts
Labels: type:enhancement, network:testnet, network:shimmer
