Repository iotaledger/explorer, pull requests merged in 2022-04, with the labels that each got.

#228 Feat: Re-implement currency drop-down selector
  api/src/clients/fixerClient.ts
  api/src/initServices.ts
  api/src/models/api/ICurrencyNamesResponse.ts
  api/src/models/clients/fixer/ISymbolsResponse.ts
  api/src/models/db/ICurrencyState.ts
  api/src/routes.ts
  api/src/routes/currency/names/get.ts
  api/src/routes/init.ts
  api/src/services/currencyService.ts
  client/src/app/components/FiatSelector.scss
  client/src/app/components/FiatSelector.tsx
  client/src/app/components/FiatSelectorState.ts
  client/src/app/components/Footer.tsx
  client/src/app/routes/Landing.tsx
  client/src/models/api/ICurrencyNamesResponse.ts
  client/src/models/services/ICurrencySettings.ts
  client/src/services/apiClient.ts
  client/src/services/currencyService.ts
Labels: v2, type:enhancement, type:ui

#230 Feat: Add label under QR code
  client/src/app/components/chrysalis/QR.scss
  client/src/app/components/chrysalis/QR.tsx
Labels: v2, type:enhancement

#177 Fix: Remove 'confirmations per second' indicator
  client/src/app/routes/Landing.scss
  client/src/app/routes/Landing.tsx
  client/src/scss/layout.scss
Labels: v2, type:fix

#182 Fix: Refine pagination
  client/src/app/components/Pagination.scss
  client/src/app/components/Pagination.tsx
  client/src/app/components/PaginationProps.ts
  client/src/app/components/PaginationState.tsx
  client/src/app/routes/chrysalis/Addr.tsx
  client/src/scss/layout.scss
Labels: v2, type:enhancement

#214 chore: remove feature request template
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: type:chore, scope:project

#213 chore: update issue template config
  .github/ISSUE_TEMPLATE/config.yml
Labels: type:chore, scope:project

#212 chore: update labels in bug report template
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: type:chore, scope:project

#163 Add inspiration credit
  client/src/app/App.scss
  client/src/app/App.tsx
Labels: v2

#209 Feat: replace icons with Material Icons
  client/public/index.html
  client/src/app/components/CurrencyButton.tsx
  client/src/app/components/FiatSelector.scss
  client/src/app/components/FiatSelector.tsx
  client/src/app/components/Header.scss
  client/src/app/components/Header.tsx
  client/src/app/components/MessageButton.scss
  client/src/app/components/MessageButton.tsx
  client/src/app/components/Modal.scss
  client/src/app/components/Modal.tsx
  client/src/app/components/NetworkSwitcher.scss
  client/src/app/components/NetworkSwitcher.tsx
  client/src/app/components/SearchInput.scss
  client/src/app/components/SearchInput.tsx
  client/src/app/components/identity/IdentityCompareDropdown.scss
  client/src/app/components/identity/IdentityCompareDropdown.tsx
  client/src/app/components/identity/IdentitySearchInput.scss
  client/src/app/components/identity/IdentitySearchInput.tsx
  client/src/app/routes/CurrencyConverter.tsx
  client/src/app/routes/IdentityResolver.scss
  client/src/app/routes/Landing.scss
  client/src/app/routes/Landing.tsx
  client/src/app/routes/Markets.tsx
  client/src/app/routes/Visualizer.scss
  client/src/app/routes/Visualizer.tsx
  client/src/app/routes/og/Address.scss
  client/src/app/routes/og/Address.tsx
  client/src/app/routes/og/Bundle.scss
  client/src/app/routes/og/Bundle.tsx
  client/src/app/routes/og/Tag.scss
  client/src/app/routes/og/Tag.tsx
  client/src/app/routes/og/Transaction.scss
  client/src/app/routes/og/Transaction.tsx
  client/src/assets/chevron-down-gray.svg
  client/src/assets/chevron-down-white.svg
  client/src/assets/chevron-left-green.svg
  client/src/assets/chevron-right-green.svg
  client/src/assets/close.svg
  client/src/assets/copy-gray.svg
  client/src/assets/dark-mode.svg
  client/src/assets/dots.svg
  client/src/assets/dropdown.svg
  client/src/assets/filter.svg
  client/src/assets/hamburger.svg
  client/src/assets/info.svg
  client/src/assets/light-mode.svg
  client/src/assets/pause.svg
  client/src/assets/play.svg
  client/src/assets/search.svg
  client/src/scss/forms.scss
Labels: v2, type:ui

#261 Feat: Add stardust specific search
  api/src/utils/stardust/searchQueryBuilder.ts
  api/src/utils/stardust/stardustTangleHelper.ts
Labels: status:donotmerge
