Repository iotaledger/explorer, pull requests merged in 2022-06, with the labels that each got.

#331 Fix: Improve amount computing for Inputs
  client/src/helpers/stardust/transactionsHelper.ts
Labels: network:shimmer

#355 Fix: Bump iota.js version
  api/package-lock.json
  api/package.json
  client/package-lock.json
  client/package.json
  client/src/app/components/stardust/MilestonePayload.tsx
  client/src/app/components/stardust/UnlockCondition.tsx
Labels: priority:1, type:feature, network:testnet

#368 Fix: Broken page navigation in browser
  client/src/services/stardust/stardustTangleCacheService.ts
Labels: type:fix, network:testnet

#371 Fix: Fix association labels in Associated Outputs Table
  client/src/app/components/stardust/AssociatedOutput.tsx
Labels: type:fix, network:testnet

#372 Feat: Add output page
  api/src/utils/stardust/stardustTangleHelper.ts
  client/src/app/App.tsx
  client/src/app/components/stardust/Feature.tsx
  client/src/app/components/stardust/FeatureProps.tsx
  client/src/app/components/stardust/FeatureState.tsx
  client/src/app/components/stardust/Output.tsx
  client/src/app/components/stardust/OutputProps.tsx
  client/src/app/components/stardust/UnlockCondition.tsx
  client/src/app/components/stardust/UnlockConditionProps.tsx
  client/src/app/components/stardust/UnlockConditionState.tsx
  client/src/app/routes/stardust/OutputPage.scss
  client/src/app/routes/stardust/OutputPage.tsx
  client/src/app/routes/stardust/OutputPageProps.ts
  client/src/app/routes/stardust/Search.tsx
  client/src/helpers/stardust/transactionsHelper.ts
Labels: type:feature, network:testnet

#369 Feat: Display output id in output
  client/src/app/components/stardust/AssociatedOutputsTable.scss
  client/src/app/components/stardust/AssociatedOutputsTable.tsx
  client/src/app/components/stardust/Feature.tsx
  client/src/app/components/stardust/Output.scss
  client/src/app/components/stardust/Output.tsx
  client/src/app/components/stardust/UnlockCondition.tsx
  client/src/app/routes/stardust/OutputPage.scss
  client/src/app/routes/stardust/OutputPage.tsx
Labels: type:enhancement, network:testnet

#373 Feat: Display glow amount on toggle.
  client/src/app/components/stardust/Input.tsx
  client/src/app/components/stardust/Output.scss
  client/src/app/components/stardust/Output.tsx
  client/src/app/components/stardust/TransactionPayload.tsx
  client/src/app/components/stardust/TransactionPayloadState.ts
  client/src/app/routes/stardust/Block.tsx
  client/src/app/routes/stardust/BlockState.ts
  client/src/scss/layout.scss
Labels: type:enhancement, network:testnet
