Repository iotaledger/explorer, pull requests merged in 2022-12, with the labels that each got.

#604 Fix: Add responsiveness to Statistics page
  client/src/app/components/stardust/statistics/ChartHeader.scss
  client/src/app/components/stardust/statistics/ChartHeader.tsx
  client/src/app/components/stardust/statistics/ChartLegend.tsx
  client/src/app/components/stardust/statistics/ChartUtils.tsx
  client/src/app/components/stardust/statistics/charts/BarChart.tsx
  client/src/app/components/stardust/statistics/charts/Chart.scss
  client/src/app/components/stardust/statistics/charts/LineChart.tsx
  client/src/app/components/stardust/statistics/charts/StackedBarChart.tsx
  client/src/app/components/stardust/statistics/charts/StackedLineChart.tsx
  client/src/app/routes/stardust/statistics/StatisticsPage.scss
  client/src/app/routes/stardust/statistics/StatisticsPage.tsx
Labels: status:donotmerge

#583 Fix: Spacing of inputs and outputs in transaction section
  client/src/app/components/DataToggle.scss
  client/src/app/components/chrysalis/TransactionPayload.tsx
  client/src/app/components/stardust/Feature.tsx
  client/src/app/components/stardust/NativeToken.tsx
  client/src/app/components/stardust/Output.scss
  client/src/app/components/stardust/Output.tsx
  client/src/app/components/stardust/TransactionPayload.scss
  client/src/app/components/stardust/TransactionPayload.tsx
  client/src/app/components/stardust/UnlockCondition.tsx
  client/src/app/components/stardust/Unlocks.tsx
  client/src/scss/card.scss
  client/src/scss/layout.scss
  client/src/scss/themes.scss
Labels: type:fix, network:testnet, network:shimmer

#589 Feat: Add date picker to download transaction history.
  api/src/models/api/stardust/ITransactionHistoryDownloadBody.ts
  api/src/routes/stardust/transactionhistory/download/post.ts
  api/src/services/stardust/chronicleService.ts
  client/src/app/components/stardust/DownloadModal.scss
  client/src/app/components/stardust/DownloadModal.tsx
  client/src/scss/themes.scss
  client/src/services/stardust/stardustApiClient.ts
Labels: type:enhancement, network:testnet

#607 Feat: Tabify the sections on Address page
  client/src/app/components/hoc/TabbedSection.scss
  client/src/app/components/hoc/TabbedSection.tsx
  client/src/app/components/stardust/AssetsTable.tsx
  client/src/app/components/stardust/AssociatedOutputs.tsx
  client/src/app/components/stardust/NftSection.scss
  client/src/app/components/stardust/NftSection.tsx
  client/src/app/components/stardust/history/TransactionHistory.tsx
  client/src/app/routes/stardust/AddressPage.scss
  client/src/app/routes/stardust/AddressPage.tsx
  client/src/app/routes/stardust/AddressPageState.tsx
  client/src/app/routes/stardust/INftDetails.ts
  client/src/app/routes/stardust/ITokenDetails.ts
  client/src/scss/section.scss
Labels: type:enhancement, type:ui, network:testnet, network:shimmer
