Repository iotaledger/explorer, pull requests merged in 2022-02, with the labels that each got.

#117 Feat: Add pagination to transaction history table
  api/src/models/api/chrysalis/ITransactionsDetailsRequest.ts
  api/src/routes/chrysalis/transactionhistory/get.ts
  api/src/utils/extendedSingleNodeClient.ts
  api/src/utils/tangleHelper.ts
  client/src/app/components/Pagination.scss
  client/src/app/components/Pagination.tsx
  client/src/app/components/PaginationProps.ts
  client/src/app/components/PaginationState.tsx
  client/src/app/components/chrysalis/TransactionPayload.tsx
  client/src/app/routes/chrysalis/Addr.tsx
  client/src/app/routes/chrysalis/AddrState.ts
  client/src/models/api/chrysalis/ITransactionsDetailsRequest.ts
  client/src/scss/themes.scss
  client/src/scss/variables.scss
  client/src/services/apiClient.ts
  client/src/services/tangleCacheService.ts
Labels: v2

#121 Feat: Adapt latest DID implementations
  client/src/app/routes/IdentityResolver.scss
  client/src/app/routes/IdentityResolver.tsx
Labels: v2

#125 Feat: Improve DID search CSS
  client/src/app/components/SearchInput.scss
  client/src/app/components/identity/IdentitySearchInput.scss
  client/src/app/components/identity/IdentitySearchInput.tsx
  client/src/app/routes/Search.scss
  client/src/app/routes/Search.tsx
  client/src/scss/themes.scss
Labels: v2, type:enhancement

#171 Fix: CSS message comparison missing in Identity Resolver
  client/src/app/components/identity/IdentityJsonCompare.scss
  client/src/app/components/identity/IdentityJsonCompare.tsx
  client/src/scss/themes.scss
Labels: v2

#170 Fix: duplicated history tsx
  client/src/app/components/chrysalis/Transaction.tsx
  client/src/app/components/chrysalis/TransactionProps.tsx
  client/src/app/routes/chrysalis/Addr.tsx
  client/src/models/api/chrysalis/ITransactionsDetailsResponse.ts
  client/src/services/tangleCacheService.ts
Labels: v2

#154 Fix: Clear search field when a search has been done
  client/src/app/components/SearchInput.tsx
Labels: v2

#176 Fix: Removed info icon from General / Replaced dots icon with info icon
  client/src/app/routes/IdentityResolver.tsx
  client/src/app/routes/chrysalis/Addr.tsx
  client/src/app/routes/chrysalis/Indexed.tsx
  client/src/app/routes/chrysalis/Message.tsx
Labels: v2

#175 Fix: identity doc display
  client/src/app/routes/IdentityResolver.tsx
Labels: v2

#174 Fix: Landing page resize (Safari)
  client/src/app/routes/Landing.scss
Labels: v2

#173 Fix: identity diff detection
  client/src/app/components/identity/tree/IdentityTreeItem.tsx
Labels: v2

#185 Fix: displaying Children title in Message tree
  client/src/app/components/MessageTree.tsx
Labels: v2, type:enhancement, priority:1
