Repository iotaledger/explorer, pull requests merged in 2022-10, with the labels that each got.

#533 Feat: Make Explorer html meta tags dynamic
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/server/index.js
  client/src/app/App.tsx
  client/src/app/AppUtils.tsx
Labels: status:donotmerge, type:enhancement, network:mainnet, network:testnet, network:legacymainnet, network:shimmer

#534 Fix: Prevent fetching IBM Plex mono font and Material icons from google
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/index.tsx
Labels: type:fix, type:ui, network:mainnet, network:testnet, network:legacymainnet, network:shimmer

#531 Fix: Disable click on tag in Tagged data payload
  client/src/app/components/stardust/TaggedDataPayload.tsx
Labels: type:fix, network:shimmer

#532 Fix: Disable identity resolver for the unsupported networks
  api/src/models/db/INetwork.ts
  api/src/routes/networks/get.ts
  client/src/app/App.tsx
  client/src/index.tsx
  client/src/models/config/IConfiguration.ts
  client/src/models/config/INetwork.ts
Labels: type:fix, network:shimmer

#529 Fix: Clickable parents in milestone view.
  client/src/app/components/stardust/MilestonePayload.tsx
  client/src/app/routes/stardust/Block.tsx
Labels: type:fix, network:shimmer

#536 feat: Make Explorer html meta tags dynamic
  client/api/index.js
  client/package-lock.json
  client/package.json
  client/public/favicon/browserconfig.xml
  client/public/favicon/favicon.ico
  client/public/favicon/iota/android-chrome-192x192.png
  client/public/favicon/iota/android-chrome-512x512.png
  client/public/favicon/iota/favicon-16x16.png
  client/public/favicon/iota/favicon-180x180.png
  client/public/favicon/iota/favicon-32x32.png
  client/public/favicon/iota/favicon.ico
  client/public/favicon/iota/site.webmanifest
  client/public/favicon/mstile-150x150.png
  client/public/favicon/shimmer/favicon-128x128.png
  client/public/favicon/shimmer/favicon-150x150.png
  client/public/favicon/shimmer/favicon-180x180.png
  client/public/favicon/shimmer/favicon-192x192.png
  client/public/favicon/shimmer/favicon-32x32.png
  client/public/favicon/shimmer/favicon-512x512.png
  client/public/favicon/shimmer/favicon.ico
  client/public/favicon/shimmer/site.webmanifest
  client/public/index.html
  client/src/app/App.tsx
  client/src/app/AppUtils.tsx
  client/vercel.json
Labels: status:donotmerge, type:enhancement, network:mainnet, network:testnet, network:legacymainnet, network:shimmer

#542 Fix: Restrict search to only valid bech32 addresses.
  api/src/utils/stardust/searchQueryBuilder.ts
  client/src/assets/modals/stardust/search/main-header.json
Labels: type:fix, network:testnet

#549 Fix: Broken message page navigation.
  client/src/app/components/chrysalis/MilestonePayload.tsx
Labels: type:fix, network:mainnet
