Repository iotaledger/explorer, pull requests merged in 2022-09, with the labels that each got.

#484 Feat: Added tooltip for special unlock conditions in associated outputs.
  client/src/app/components/Tooltip.scss
  client/src/app/components/stardust/AssociatedOutput.tsx
  client/src/app/components/stardust/Output.scss
  client/src/app/components/stardust/Output.tsx
  client/src/helpers/stardust/nameHelper.ts
  client/src/scss/layout.scss
Labels: type:enhancement, network:testnet

#486 Fix: Milestone payload metadata display and conditional balance styling.
  client/src/app/components/stardust/AddressBalance.scss
  client/src/app/components/stardust/AddressBalance.tsx
  client/src/app/components/stardust/MilestonePayload.tsx
Labels: type:fix, type:ui, network:testnet

#489 Feat: Improve Address page loading
  api/src/models/api/stardust/IAddressBasicOutputsRequest.ts
  api/src/models/api/stardust/IAddressBasicOutputsResponse.ts
  api/src/models/api/stardust/ISearchResponse.ts
  api/src/routes.ts
  api/src/routes/stardust/address/balance/chronicle/get.ts
  api/src/routes/stardust/address/balance/get.ts
  api/src/routes/stardust/address/basic-outputs/get.ts
  api/src/utils/stardust/searchQueryBuilder.ts
  api/src/utils/stardust/stardustTangleHelper.ts
  client/src/app/components/stardust/AssociatedOutputsTable.tsx
  client/src/app/components/stardust/history/TransactionHistory.tsx
  client/src/app/routes/stardust/AddressPage.scss
  client/src/app/routes/stardust/AddressPage.tsx
  client/src/app/routes/stardust/Alias.tsx
  client/src/app/routes/stardust/Nft.tsx
  client/src/app/routes/stardust/NftSection.tsx
  client/src/app/routes/stardust/Search.tsx
  client/src/helpers/promise/AsyncProps.ts
  client/src/helpers/promise/AsyncState.ts
  client/src/helpers/promise/promiseMonitor.test.ts
  client/src/helpers/promise/promiseMonitor.ts
  client/src/models/api/stardust/IAddressBasicOutputsRequest.ts
  client/src/models/api/stardust/IAddressBasicOutputsResponse.ts
  client/src/models/api/stardust/IAddressDetailsWithBalance.ts
  client/src/models/api/stardust/ISearchResponse.ts
  client/src/services/stardust/stardustApiClient.ts
  client/src/services/stardust/stardustTangleCacheService.ts
Labels: type:enhancement, network:testnet, network:shimmer

#500 Feat(api): Support JWT auth for chronicle analyics requests
  api/src/models/db/INetwork.ts
  api/src/services/stardust/chronicleService.ts
Labels: type:enhancement, network:testnet, network:shimmer

#499 Fix(client): Fix navigating to base client route
  client/src/app/App.tsx
Labels: type:fix, network:testnet, network:shimmer

#498 Feat: Add storage rent balance on AddressPage and Alias address page
  api/src/models/api/stardust/INodeInfoResponse.ts
  api/src/routes.ts
  api/src/routes/stardust/address/outputs/get.ts
  api/src/services/stardust/nodeInfoService.ts
  api/src/utils/stardust/stardustTangleHelper.ts
  client/src/app/AppUtils.tsx
  client/src/app/components/stardust/AddressBalance.scss
  client/src/app/components/stardust/Output.tsx
  client/src/app/context/NetworkContext.ts
  client/src/app/routes/stardust/AddressPage.tsx
  client/src/app/routes/stardust/AddressPageState.tsx
  client/src/app/routes/stardust/Alias.tsx
  client/src/app/routes/stardust/AliasState.tsx
  client/src/app/routes/stardust/Nft.tsx
  client/src/app/routes/stardust/NftSection.tsx
  client/src/helpers/stardust/transactionsHelper.ts
  client/src/models/api/stardust/INodeInfoResponse.ts
  client/src/services/nodeInfoService.ts
  client/src/services/stardust/stardustApiClient.ts
  client/src/services/stardust/stardustTangleCacheService.ts
Labels: type:feature, network:testnet, network:shimmer

#501 Fix: GitHub workflows updated to latest node and npm versions
  .github/workflows/api-prod.yaml
  .github/workflows/api-shimmer-prod.yaml
  .github/workflows/api-shimmer-staging.yaml
  .github/workflows/api-staging.yaml
  .github/workflows/bot-prod.yaml
  .github/workflows/client-prod.yaml
  .github/workflows/client-shimmer-prod.yaml
  .github/workflows/client-shimmer-staging.yaml
  .github/workflows/client-staging.yaml
Labels: type:enhancement, network:testnet, network:shimmer

#487 Feat: Add milestones feed on Landing
  api/src/models/api/stardust/ISearchResponse.ts
  api/src/models/api/stardust/milestone/IMilestoneDetailsRequest.ts
  api/src/models/api/stardust/milestone/IMilestoneDetailsResponse.ts
  api/src/models/api/stardust/milestone/IMilestoneStatsRequest.ts
  api/src/models/api/stats/IMilestoneAnalyticStats.ts
  api/src/models/db/IAnalyticsStore.ts
  api/src/routes.ts
  api/src/routes/analytics/get.ts
  api/src/routes/stardust/milestone/get.ts
  api/src/routes/stardust/milestone/stats/get.ts
  api/src/services/stardust/baseStatsService.ts
  api/src/services/stardust/chronicleService.ts
  api/src/utils/stardust/stardustTangleHelper.ts
  client/src/app/App.tsx
  client/src/app/components/FeedInfo.tsx
  client/src/app/components/FeedMilestoneInfo.scss
  client/src/app/components/FeedMilestoneInfo.tsx
  client/src/app/components/chrysalis/Feeds.tsx
  client/src/app/components/chrysalis/FeedsState.ts
  client/src/app/components/chrysalis/SidePanel.tsx
  client/src/app/components/chrysalis/SidePanelState.ts
  client/src/app/components/stardust/Feeds.tsx
  client/src/app/components/stardust/FeedsState.ts
  client/src/app/routes.tsx
  client/src/app/routes/VisualizerState.ts
  client/src/app/routes/chrysalis/Landing.tsx
  client/src/app/routes/chrysalis/LandingState.ts
  client/src/app/routes/stardust/Landing.scss
  client/src/app/routes/stardust/Landing.tsx
  client/src/app/routes/stardust/LandingState.ts
  client/src/app/routes/stardust/landing/AnalyticStats.scss
  client/src/app/routes/stardust/landing/AnalyticStats.tsx
  client/src/app/routes/stardust/landing/BlockFeed.scss
  client/src/app/routes/stardust/landing/BlockFeed.tsx
  client/src/app/routes/stardust/landing/FeedFilterUtils.tsx
  client/src/app/routes/stardust/landing/FeedFilters.scss
  client/src/app/routes/stardust/landing/FeedFilters.tsx
  client/src/app/routes/stardust/landing/InfoBox.scss
  client/src/app/routes/stardust/landing/InfoBox.tsx
  client/src/app/routes/stardust/landing/Landing.scss
  client/src/app/routes/stardust/landing/Landing.tsx
  client/src/app/routes/stardust/landing/LandingState.ts
  client/src/app/routes/stardust/landing/MilestoneFeed.scss
  client/src/app/routes/stardust/landing/MilestoneFeed.tsx
  client/src/helpers/hooks/useMilestoneInterval.ts
  client/src/index.tsx
  client/src/models/api/stardust/IMilestoneStatsRequest.ts
  client/src/models/api/stardust/ISearchResponse.ts
  client/src/models/api/stats/IMilestoneAnalyticStats.ts
  client/src/models/services/IFilterSettings.ts
  client/src/models/services/filterField.ts
  client/src/models/services/stardust/IFilterSettings.ts
  client/src/scss/themes.scss
  client/src/services/stardust/stardustApiClient.ts
  client/src/services/stardust/stardustFeedClient.ts
  client/src/services/stardust/stardustTangleCacheService.ts
Labels: status:blocked, type:feature, network:testnet, network:shimmer

#510 Fix: Css of storage rent when it is zero
  client/src/app/routes/stardust/AddressPage.tsx
Labels: type:fix, type:ui, network:testnet, network:shimmer

#497 Feat: Statistic page placeholder
  client/package-lock.json
  client/package.json
  client/src/app/App.tsx
  client/src/app/AppUtils.tsx
  client/src/app/routes/stardust/Statistic.scss
  client/src/app/routes/stardust/Statistic.tsx
  client/src/helpers/stardust/mockDailyTransactions.ts
Labels: type:feature, type:ui, network:shimmer

#511 feat: Add support for feeding Shimmer claiming stats
  api/src/models/api/stats/IAnalyticStats.ts
  api/src/models/api/stats/IMilestoneAnalyticStats.ts
  api/src/models/api/stats/IShimmerClaimed.ts
  api/src/models/db/INetwork.ts
  api/src/models/services/stardust/IShimmerClaimedResponse.ts
  api/src/models/services/stardust/IShimmerStatsService.ts
  api/src/routes.ts
  api/src/routes/analytics/get.ts
  api/src/routes/networks/get.ts
  api/src/routes/stardust/analytics/get.ts
  api/src/routes/stardust/analytics/shimmer/get.ts
  api/src/services/stardust/baseStatsService.ts
  api/src/services/stardust/chronicleService.ts
  api/src/services/stardust/stardustStatsService.ts
  client/src/app/components/stardust/Feeds.tsx
  client/src/app/components/stardust/FeedsState.ts
  client/src/app/routes/stardust/landing/AnalyticStats.scss
  client/src/app/routes/stardust/landing/AnalyticStats.tsx
  client/src/app/routes/stardust/landing/Landing.tsx
  client/src/app/routes/stardust/landing/ShimmerClaimedUtils.spec.ts
  client/src/app/routes/stardust/landing/ShimmerClaimedUtils.ts
  client/src/helpers/bigDecimal.spec.ts
  client/src/helpers/bigDecimal.ts
  client/src/helpers/stardust/valueFormatHelper.ts
  client/src/models/api/IChronicleResponse.ts
  client/src/models/api/stats/IAnalyticStats.ts
  client/src/models/api/stats/IShimmerClaimed.ts
  client/src/models/config/INetwork.ts
  client/src/services/stardust/stardustApiClient.ts
Labels: priority:1, type:feature, network:testnet, network:shimmer
