Repository iotaledger/explorer, pull requests merged in 2022-08, with the labels that each got.

#432 Feat: Transaction payload Inputs rework
  client/src/app/components/stardust/Input.tsx
  client/src/app/components/stardust/Output.scss
  client/src/app/components/stardust/Output.tsx
  client/src/app/components/stardust/TransactionPayload.scss
  client/src/app/components/stardust/TransactionPayload.tsx
  client/src/app/components/stardust/TransactionPayloadProps.tsx
  client/src/app/components/stardust/Unlocks.tsx
  client/src/app/routes/stardust/Block.tsx
  client/src/app/routes/stardust/BlockState.ts
  client/src/app/routes/stardust/TransactionPage.tsx
  client/src/app/routes/stardust/TransactionPageState.ts
  client/src/helpers/stardust/transactionsHelper.ts
  client/src/models/api/stardust/IInput.ts
  client/src/models/api/stardust/IOutput.ts
Labels: type:enhancement, network:testnet, network:shimmer

#436 Fix: Expand only the clicked native token
  client/src/app/components/stardust/NativeToken.tsx
  client/src/app/components/stardust/NativeTokenProps.ts
  client/src/app/components/stardust/NativeTokenState.ts
  client/src/app/components/stardust/Output.tsx
  client/src/app/components/stardust/OutputState.tsx
Labels: type:fix, network:testnet

#437 Fix: Rename message to block for stardust.
  api/src/models/api/IMilestonesGetResponse.ts
  api/src/models/api/stardust/IBlockDetailsRequest.ts
  api/src/models/db/IMilestoneStore.ts
  client/src/app/components/stardust/MilestonePayload.tsx
  client/src/app/routes/stardust/BlockState.ts
  client/src/app/routes/stardust/LandingState.ts
  client/src/app/routes/stardust/Search.tsx
  client/src/app/routes/stardust/TransactionPageState.ts
  client/src/helpers/stardust/transactionsHelper.ts
  client/src/models/api/IMilestonesGetResponse.ts
  client/src/models/api/chrysalis/IMessageDetailsRequest.ts
  client/src/models/api/stardust/IMessageDetails.ts
  client/src/services/chrysalis/chrysalisApiClient.ts
Labels: type:fix, network:testnet

#435 Fix: Format balance to two decimal places without rounding off
  client/src/helpers/stardust/valueFormatHelper.ts
Labels: type:fix, network:testnet

#440 Fix: Make "spent in transaction" a link and copiable in OutputPage
  client/src/app/routes/stardust/Block.tsx
  client/src/app/routes/stardust/OutputPage.tsx
  client/src/app/routes/stardust/TransactionPage.tsx
Labels: type:fix, network:testnet

#422 Fix: Swap node and chronicle in API requests
  api/src/utils/stardust/stardustTangleHelper.ts
Labels: status:donotmerge, network:testnet, network:shimmer

#454 Fix: Include ALIAS and NFT unlock types when computing block signatures
  client/src/helpers/stardust/transactionsHelper.ts
Labels: type:fix, network:testnet

#453 Fix: Fix market cap off by factor of 10
  client/src/services/currencyService.ts
Labels: type:fix, network:mainnet, network:testnet, network:shimmer, bug report, context:markets

#458 Feat: Add amount column in associated outputs
  client/src/app/components/stardust/AssociatedOutput.tsx
  client/src/app/components/stardust/AssociatedOutputsTable.scss
  client/src/app/components/stardust/AssociatedOutputsTable.tsx
Labels: type:feature, network:testnet

#456 Feat: Use Chronicle for indexer calls
  api/src/utils/stardust/stardustTangleHelper.ts
  client/src/app/routes/stardust/AddressPage.tsx
Labels: type:enhancement, network:testnet, network:shimmer

#460 Feat: Added time passed since the output created in associated outputs table
  client/src/app/components/stardust/AssociatedOutput.tsx
Labels: type:enhancement, network:testnet

#463 Feat: Truncate output id in Output component
  client/src/app/components/CopyButton.scss
  client/src/app/components/CopyButton.tsx
  client/src/app/components/CopyButtonProps.tsx
  client/src/app/components/CopyButtonState.tsx
  client/src/app/components/chrysalis/Bech32Address.tsx
  client/src/app/components/chrysalis/Output.tsx
  client/src/app/components/chrysalis/TransactionPayload.tsx
  client/src/app/components/stardust/Address.tsx
  client/src/app/components/stardust/AddressBalance.tsx
  client/src/app/components/stardust/AssociatedOutputsTable.scss
  client/src/app/components/stardust/Bech32Address.tsx
  client/src/app/components/stardust/Output.scss
  client/src/app/components/stardust/Output.tsx
  client/src/app/components/stardust/OutputProps.tsx
  client/src/app/components/stardust/TransactionPayload.scss
  client/src/app/routes/IdentityResolver.tsx
  client/src/app/routes/StreamsV0.tsx
  client/src/app/routes/chrysalis/Addr.tsx
  client/src/app/routes/chrysalis/Message.tsx
  client/src/app/routes/og/Address.tsx
  client/src/app/routes/og/Bundle.tsx
  client/src/app/routes/og/Tag.tsx
  client/src/app/routes/og/Transaction.tsx
  client/src/app/routes/stardust/Block.tsx
  client/src/app/routes/stardust/Foundry.tsx
  client/src/app/routes/stardust/NftRegistryDetails.tsx
  client/src/app/routes/stardust/OutputPage.tsx
  client/src/app/routes/stardust/TransactionPage.tsx
Labels: type:enhancement, type:ui

#462 Feat: Integrate chronicle analytic network stats
  api/package-lock.json
  api/package.json
  api/src/initServices.ts
  api/src/models/api/stats/IAnalyticStats.ts
  api/src/models/api/stats/IAnalyticStatsRequest.ts
  api/src/models/db/IAnalyticsStore.ts
  api/src/models/db/IDailyMilestones.ts
  api/src/models/services/stardust/IAnalyticsStatsService.ts
  api/src/routes.ts
  api/src/routes/analytics/get.ts
  api/src/routes/init.ts
  api/src/routes/stats/get.ts
  api/src/services/chrysalis/baseStatsService.ts
  api/src/services/chrysalis/chrysalisStatsService.ts
  api/src/services/og/ogStatsService.ts
  api/src/services/stardust/baseStatsService.ts
  api/src/services/stardust/chronicleService.ts
  api/src/services/stardust/stardustStatsService.ts
  client/src/app/App.tsx
  client/src/app/AppState.ts
  client/src/app/AppUtils.tsx
  client/src/app/components/FeedsState.ts
  client/src/app/components/stardust/Feeds.tsx
  client/src/app/routes.tsx
  client/src/app/routes/stardust/InfoSection.tsx
  client/src/app/routes/stardust/Landing.tsx
  client/src/helpers/routeBuilder.ts
  client/src/models/api/stats/IAnalyticStats.ts
  client/src/models/api/stats/IAnalyticStatsRequest.ts
  client/src/services/nodeInfoService.ts
  client/src/services/stardust/stardustApiClient.ts
Labels: type:feature, network:testnet, network:shimmer

#465 Fix: Add spinner for address page
  client/src/app/routes/stardust/AddressPage.scss
  client/src/app/routes/stardust/AddressPage.tsx
Labels: type:fix, network:testnet
