Repository iotaledger/explorer, pull requests merged in 2022-07, with the labels that each got.

#377 Feat: Add dedicated Transaction Page.
  api/src/models/api/stardust/ISearchResponse.ts
  api/src/models/api/stardust/ITransactionDetailsRequest.ts
  api/src/models/api/stardust/ITransactionDetailsResponse.ts
  api/src/routes.ts
  api/src/routes/stardust/transaction/get.ts
  api/src/utils/stardust/searchQueryBuilder.ts
  api/src/utils/stardust/stardustTangleHelper.ts
  client/src/app/App.tsx
  client/src/app/components/chrysalis/InclusionState.tsx
  client/src/app/components/chrysalis/InclusionStateProps.tsx
  client/src/app/components/stardust/InclusionState.tsx
  client/src/app/components/stardust/TransactionPayload.tsx
  client/src/app/components/stardust/TransactionPayloadProps.tsx
  client/src/app/routes/chrysalis/Message.tsx
  client/src/app/routes/stardust/Block.scss
  client/src/app/routes/stardust/Block.tsx
  client/src/app/routes/stardust/BlockState.ts
  client/src/app/routes/stardust/Search.tsx
  client/src/app/routes/stardust/TransactionPage.scss
  client/src/app/routes/stardust/TransactionPage.tsx
  client/src/app/routes/stardust/TransactionPageProps.ts
  client/src/app/routes/stardust/TransactionPageState.ts
  client/src/models/api/stardust/ISearchResponse.ts
  client/src/models/api/stardust/ITransactionDetailsRequest.ts
  client/src/models/api/stardust/ITransactionDetailsResponse.ts
  client/src/models/tangleStatus.ts
  client/src/scss/themes.scss
  client/src/services/stardust/stardustApiClient.ts
  client/src/services/stardust/stardustTangleCacheService.ts
Labels: type:enhancement, network:testnet

#379 Feat: Group Associated Outputs
  api/src/models/api/stardust/IAssociatedOutputsResponse.ts
  api/src/routes/stardust/output/associated/post.ts
  api/src/utils/stardust/associatedOutputsHelper.ts
  client/src/app/components/Tooltip.scss
  client/src/app/components/Tooltip.tsx
  client/src/app/components/stardust/AssociatedOutput.tsx
  client/src/app/components/stardust/AssociatedOutputsTable.scss
  client/src/app/components/stardust/AssociatedOutputsTable.tsx
  client/src/models/api/stardust/IAssociatedOutputsResponse.ts
Labels: network:testnet

#380 Feat: Outputs page
  api/src/models/api/stardust/ISearchResponse.ts
  api/src/utils/stardust/stardustTangleHelper.ts
  client/src/app/App.tsx
  client/src/app/components/DataToggle.tsx
  client/src/app/components/DataToggleProps.tsx
  client/src/app/components/DataToggleState.tsx
  client/src/app/components/chrysalis/IndexationPayload.tsx
  client/src/app/components/chrysalis/IndexationPayloadProps.tsx
  client/src/app/components/chrysalis/IndexationPayloadState.tsx
  client/src/app/components/stardust/Feature.tsx
  client/src/app/components/stardust/TaggedDataPayload.tsx
  client/src/app/components/stardust/TaggedDataPayloadState.tsx
  client/src/app/routes/SearchState.ts
  client/src/app/routes/chrysalis/Indexed.tsx
  client/src/app/routes/chrysalis/IndexedState.ts
  client/src/app/routes/stardust/Alias.tsx
  client/src/app/routes/stardust/AliasState.tsx
  client/src/app/routes/stardust/OutputList.scss
  client/src/app/routes/stardust/OutputList.tsx
  client/src/app/routes/stardust/OutputListProps.ts
  client/src/app/routes/stardust/Search.tsx
  client/src/models/api/stardust/ISearchResponse.ts
  client/src/services/stardust/stardustTangleCacheService.ts
Labels: type:enhancement, network:testnet

#382 Feat: Hide Fiat price metrics for Alpha/Testnet
  client/src/app/App.tsx
  client/src/app/components/NetworkSwitcher.tsx
  client/src/app/components/header/Header.tsx
  client/src/app/components/stardust/TransactionPayload.tsx
  client/src/app/routes/stardust/AddressPage.tsx
  client/src/app/routes/stardust/Block.tsx
  client/src/app/routes/stardust/Foundry.tsx
  client/src/app/routes/stardust/Landing.tsx
  client/src/helpers/networkHelper.ts
  client/src/models/config/networkType.ts
Labels: network:testnet

#386 Fix: Display correct immutable features type name.
  client/src/app/components/stardust/Feature.tsx
  client/src/app/components/stardust/FeatureProps.tsx
  client/src/app/components/stardust/Output.tsx
  client/src/helpers/stardust/nameHelper.ts
Labels: type:fix, network:testnet

#391 Feat: Harmonize main landing page metrics
  client/src/app/components/chrysalis/Feeds.tsx
  client/src/app/components/stardust/Feeds.tsx
  client/src/app/routes/Landing.scss
  client/src/app/routes/chrysalis/Landing.tsx
Labels: network:testnet

#395 Feat: Harmonize extended landing page metrics
  client/src/app/components/header/Header.tsx
  client/src/app/routes/Landing.scss
  client/src/app/routes/chrysalis/Landing.scss
  client/src/app/routes/chrysalis/Landing.tsx
  client/src/app/routes/stardust/InfoSection.tsx
  client/src/app/routes/stardust/Landing.scss
  client/src/app/routes/stardust/Landing.tsx
Labels: type:feature, type:ui, network:testnet, network:shimmer

#398 Chore: Update iota & mqtt dependencies
  api/package-lock.json
  api/package.json
  api/src/initServices.ts
  api/src/models/api/chrysalis/IFeedItemMetadata.ts
  api/src/models/api/chrysalis/IFeedSubscriptionItem.ts
  api/src/models/api/stardust/IFeedItemMetadata.ts
  api/src/models/api/stardust/IFeedSubscriptionItem.ts
  api/src/models/services/chrysalis/IItemsService.ts
  api/src/models/services/stardust/IItemsService.ts
  api/src/routes/feed/subscribe.ts
  api/src/routes/feed/unsubscribe.ts
  api/src/services/chrysalis/chrysalisItemsService.ts
  api/src/services/og/ogItemsService.ts
  api/src/services/stardust/stardustItemsService.ts
  client/package-lock.json
  client/package.json
Labels: network:testnet, network:shimmer

#400 Feat: Bug fixes + UI polish
  api/src/utils/stardust/stardustTangleHelper.ts
  client/src/app/App.scss
  client/src/app/App.tsx
  client/src/app/components/DataToggle.scss
  client/src/app/components/NetworkSwitcher.scss
  client/src/app/components/NetworkSwitcher.tsx
  client/src/app/components/header/Header.scss
  client/src/app/components/header/Header.tsx
  client/src/app/components/stardust/AssociatedOutputsTable.scss
  client/src/app/components/stardust/AssociatedOutputsTable.tsx
  client/src/app/components/stardust/Feature.tsx
  client/src/app/components/stardust/Nft.scss
  client/src/app/components/stardust/Nft.tsx
  client/src/app/components/stardust/Output.tsx
  client/src/app/components/stardust/UnlockCondition.tsx
  client/src/app/components/stardust/UnlockConditionState.tsx
  client/src/app/components/stardust/history/TransactionHistory.scss
  client/src/app/components/stardust/history/TransactionHistory.tsx
  client/src/app/routes/chrysalis/Landing.tsx
  client/src/app/routes/stardust/AddressPage.scss
  client/src/app/routes/stardust/AddressPage.tsx
  client/src/app/routes/stardust/AddressPageState.tsx
  client/src/app/routes/stardust/Foundry.tsx
  client/src/app/routes/stardust/Landing.scss
  client/src/app/routes/stardust/Landing.tsx
  client/src/app/routes/stardust/LandingState.ts
  client/src/app/routes/stardust/NFTDetails.scss
  client/src/app/routes/stardust/NFTDetails.tsx
  client/src/app/routes/stardust/Nft.tsx
  client/src/app/routes/stardust/NftSection.tsx
  client/src/app/routes/stardust/Search.tsx
  client/src/app/routes/stardust/Visualizer.tsx
  client/src/helpers/dateHelper.ts
  client/src/scss/section.scss
  client/src/scss/themes.scss
Labels: network:testnet, network:shimmer

#406 Fix: Improve UI consistency on mobile devices
  client/src/app/components/Pagination.scss
  client/src/app/components/footer/ShimmerFooter.scss
  client/src/app/routes/stardust/AddressPage.scss
  client/src/app/routes/stardust/AddressPage.tsx
  client/src/app/routes/stardust/Landing.scss
Labels: type:fix, type:ui, network:testnet

#413 Feat: Update visualizer info labels.
  client/src/app/routes/stardust/Visualizer.tsx
Labels: type:enhancement, network:testnet, context:visualizer

#419 Feat: Update Visualizer (stardust)
  client/src/app/App.tsx
  client/src/app/routes/VisualizerState.ts
  client/src/app/routes/chrysalis/Visualizer.scss
  client/src/app/routes/chrysalis/Visualizer.tsx
  client/src/app/routes/stardust/Visualizer.scss
  client/src/app/routes/stardust/Visualizer.tsx
  client/src/assets/close.svg
  client/src/helpers/nodeShader.ts
  client/src/scss/themes.scss
Labels: type:enhancement, network:testnet, network:shimmer

#423 Feat: Improve Feed Info seconds
  client/src/app/components/FeedInfo.tsx
Labels: network:testnet, network:shimmer

#426 Feat: Improve Alias, Foundry and Nft Routes
  api/src/models/api/stardust/IAliasRequest.ts
  api/src/models/api/stardust/IAliasResponse.ts
  api/src/models/api/stardust/ISearchResponse.ts
  api/src/models/api/stardust/foundry/IFoundriesRequest.ts
  api/src/models/api/stardust/foundry/IFoundriesResponse.ts
  api/src/models/api/stardust/foundry/IFoundryRequest.ts
  api/src/models/api/stardust/foundry/IFoundryResponse.ts
  api/src/models/api/stardust/nft/INftDetailsRequest.ts
  api/src/models/api/stardust/nft/INftDetailsResponse.ts
  api/src/models/api/stardust/nft/INftOutputsRequest.ts
  api/src/models/api/stardust/nft/INftOutputsResponse.ts
  api/src/models/api/stardust/nft/INftRegistryDetailsRequest.ts
  api/src/models/api/stardust/nft/INftRegistryDetailsResponse.ts
  api/src/routes.ts
  api/src/routes/stardust/alias/foundries/get.ts
  api/src/routes/stardust/alias/get.ts
  api/src/routes/stardust/foundry/get.ts
  api/src/routes/stardust/nft/details/get.ts
  api/src/routes/stardust/nft/outputs/get.ts
  api/src/routes/stardust/nft/registry/get.ts
  api/src/utils/stardust/stardustTangleHelper.ts
  client/package-lock.json
  client/package.json
  client/src/app/App.tsx
  client/src/app/components/DataToggle.scss
  client/src/app/components/DataToggle.tsx
  client/src/app/components/stardust/Feature.tsx
  client/src/app/components/stardust/Nft.tsx
  client/src/app/components/stardust/Output.tsx
  client/src/app/routes/AliasRouteProps.ts
  client/src/app/routes/NftRouteProps.ts
  client/src/app/routes/stardust/Alias.tsx
  client/src/app/routes/stardust/Foundry.scss
  client/src/app/routes/stardust/Foundry.tsx
  client/src/app/routes/stardust/FoundryProps.ts
  client/src/app/routes/stardust/Nft.scss
  client/src/app/routes/stardust/Nft.tsx
  client/src/app/routes/stardust/NftRegistryDetails.scss
  client/src/app/routes/stardust/NftRegistryDetails.tsx
  client/src/app/routes/stardust/NftRegistryDetailsProps.ts
  client/src/app/routes/stardust/NftRegistryDetailsState.ts
  client/src/app/routes/stardust/OutputPage.tsx
  client/src/app/routes/stardust/Search.tsx
  client/src/models/api/stardust/IAliasRequest.ts
  client/src/models/api/stardust/IAliasResponse.ts
  client/src/models/api/stardust/ISearchResponse.ts
  client/src/models/api/stardust/foundry/IFoundriesRequest.ts
  client/src/models/api/stardust/foundry/IFoundriesResponse.ts
  client/src/models/api/stardust/foundry/IFoundryRequest.ts
  client/src/models/api/stardust/foundry/IFoundryResponse.ts
  client/src/models/api/stardust/nft/INftDetailsRequest.ts
  client/src/models/api/stardust/nft/INftDetailsResponse.ts
  client/src/models/api/stardust/nft/INftOutputsRequest.ts
  client/src/models/api/stardust/nft/INftOutputsResponse.ts
  client/src/models/api/stardust/nft/INftRegistryDetailsRequest.ts
  client/src/models/api/stardust/nft/INftRegistryDetailsResponse.ts
  client/src/scss/card.scss
  client/src/services/stardust/stardustApiClient.ts
  client/src/services/stardust/stardustTangleCacheService.ts
Labels: type:enhancement, network:testnet, network:shimmer
