Repository iotaledger/explorer, pull requests merged in 2023-03, with the labels that each got.

#701 Feat: Tabify sections on Transaction page
  client/src/app/routes/stardust/TransactionPage.scss
  client/src/app/routes/stardust/TransactionPage.tsx
Labels: type:enhancement, network:shimmer

#696 Feat: Tabify sections on foundry page
  client/src/app/routes/stardust/Foundry.tsx
Labels: type:enhancement, network:shimmer

#704 Fix: Updated wording for block metadata
  client/src/app/components/stardust/InclusionState.tsx
  client/src/app/components/stardust/block/section/BlockMetadataSection.tsx
  client/src/app/routes/stardust/TransactionPage.tsx
Labels: type:fix, network:testnet, network:shimmer

#700 Feat: Sort referenced blocks and add block's children to block metadata section
  api/src/models/api/stardust/IBlockChildrenResponse.ts
  api/src/models/api/stardust/milestone/IMilestoneBlocksResponse.ts
  api/src/routes.ts
  api/src/routes/stardust/block/children/get.ts
  api/src/services/stardust/chronicleService.ts
  client/src/app/components/stardust/block/section/BlockMetadataSection.tsx
  client/src/app/routes/stardust/Block.tsx
  client/src/app/routes/stardust/TransactionPage.tsx
  client/src/app/routes/stardust/TransactionPageState.ts
  client/src/helpers/hooks/useBlockChildren.ts
  client/src/models/api/stardust/IBlockChildrenRequest.ts
  client/src/models/api/stardust/IBlockChildrenResponse.ts
  client/src/models/api/stardust/block/IBlockDetailsResponse.ts
  client/src/services/stardust/stardustApiClient.ts
  client/src/services/stardust/stardustTangleCacheService.ts
Labels: status:donotmerge
